// Generated by gambit-game-studio — game info / paytable data.
export const gameMeta = {
  "gameName": "Kaise Bani",
  "gameId": "kaise_bani",
  "version": "KB92026100",
  "studioName": "Atomic-Labs",
  "tagline": "Back a Winner, Claim the Crown",
  "rtp": "97.00%",
  "maxWin": "2,500×",
  "reels": 7,
  "rows": 7,
  "volatility": "Medium",
  "minCluster": 5,
  "about": "Play Kaise Bani — a 7×7 pay-anywhere adventure where 5 or more matching symbols land a win from anywhere on the reels. Winning symbols tumble away and fresh ones drop in for chained wins, with a top prize of 2,500× your total bet.",
  "pays": [
    {
      "name": "H1",
      "label": "High 1",
      "tiers": [
        [
          5,
          5
        ],
        [
          6,
          12
        ],
        [
          9,
          25
        ],
        [
          13,
          55
        ]
      ]
    },
    {
      "name": "H2",
      "label": "High 2",
      "tiers": [
        [
          5,
          2.5
        ],
        [
          6,
          6.5
        ],
        [
          9,
          13
        ],
        [
          13,
          35
        ]
      ]
    },
    {
      "name": "H3",
      "label": "High 3",
      "tiers": [
        [
          5,
          1.5
        ],
        [
          6,
          3.5
        ],
        [
          9,
          8
        ],
        [
          13,
          25
        ]
      ]
    },
    {
      "name": "H4",
      "label": "High 4",
      "tiers": [
        [
          5,
          1
        ],
        [
          6,
          2.5
        ],
        [
          9,
          6
        ],
        [
          13,
          18
        ]
      ]
    },
    {
      "name": "L1",
      "label": "Low 1",
      "tiers": [
        [
          5,
          0.5
        ],
        [
          6,
          1.5
        ],
        [
          9,
          4
        ],
        [
          13,
          10
        ]
      ]
    },
    {
      "name": "L2",
      "label": "Low 2",
      "tiers": [
        [
          5,
          0.3
        ],
        [
          6,
          1
        ],
        [
          9,
          3
        ],
        [
          13,
          7
        ]
      ]
    },
    {
      "name": "L3",
      "label": "Low 3",
      "tiers": [
        [
          5,
          0.2
        ],
        [
          6,
          0.6
        ],
        [
          9,
          2
        ],
        [
          13,
          5
        ]
      ]
    },
    {
      "name": "L4",
      "label": "Low 4",
      "tiers": [
        [
          5,
          0.1
        ],
        [
          6,
          0.4
        ],
        [
          9,
          1.2
        ],
        [
          13,
          3.5
        ]
      ]
    }
  ],
  "specials": [
    {
      "name": "S",
      "label": "Scatter",
      "desc": "Lands the Free Spins bonus when enough appear anywhere on the reels."
    },
    {
      "name": "W",
      "label": "Wild",
      "desc": "Substitutes for any paying symbol to help complete wins."
    }
  ]
} as const;
