// Generated by gambit-game-studio — game info / paytable data.
export const gameMeta = {
  "gameName": "Skull Fiesta Frenzy",
  "studioName": "Atomic-Labs",
  "tagline": "Back a Winner, Claim the Crown",
  "rtp": "97.00%",
  "maxWin": "5,000×",
  "reels": 7,
  "rows": 7,
  "volatility": "High",
  "about": "Play Skull Fiesta Frenzy — a 7×7 pay-anywhere adventure where 8 or more matching symbols land a win from anywhere on the reels. Winning symbols tumble away and fresh ones drop in for chained wins, with a top prize of 5,000× your total bet.",
  "pays": [
    {
      "name": "H1",
      "label": "High 1",
      "tiers": [
        [
          5,
          3
        ],
        [
          6,
          7.5
        ],
        [
          9,
          15
        ],
        [
          13,
          60
        ]
      ]
    },
    {
      "name": "H2",
      "label": "High 2",
      "tiers": [
        [
          5,
          2
        ],
        [
          6,
          5
        ],
        [
          9,
          10
        ],
        [
          13,
          40
        ]
      ]
    },
    {
      "name": "H3",
      "label": "High 3",
      "tiers": [
        [
          5,
          1.3
        ],
        [
          6,
          3.2
        ],
        [
          9,
          7
        ],
        [
          13,
          30
        ]
      ]
    },
    {
      "name": "H4",
      "label": "High 4",
      "tiers": [
        [
          5,
          1
        ],
        [
          6,
          2.5
        ],
        [
          9,
          6
        ],
        [
          13,
          20
        ]
      ]
    },
    {
      "name": "L1",
      "label": "Low 1",
      "tiers": [
        [
          5,
          0.6
        ],
        [
          6,
          1.5
        ],
        [
          9,
          4
        ],
        [
          13,
          10
        ]
      ]
    },
    {
      "name": "L2",
      "label": "Low 2",
      "tiers": [
        [
          5,
          0.4
        ],
        [
          6,
          1.2
        ],
        [
          9,
          3.5
        ],
        [
          13,
          8
        ]
      ]
    },
    {
      "name": "L3",
      "label": "Low 3",
      "tiers": [
        [
          5,
          0.2
        ],
        [
          6,
          0.8
        ],
        [
          9,
          2.5
        ],
        [
          13,
          5
        ]
      ]
    },
    {
      "name": "L4",
      "label": "Low 4",
      "tiers": [
        [
          5,
          0.1
        ],
        [
          6,
          0.5
        ],
        [
          9,
          1.5
        ],
        [
          13,
          4
        ]
      ]
    }
  ],
  "specials": [
    {
      "name": "S",
      "label": "Scatter",
      "desc": "Lands the Free Spins bonus when enough appear anywhere on the reels."
    },
    {
      "name": "W",
      "label": "Wild",
      "desc": "Substitutes for any paying symbol to help complete wins."
    }
  ]
} as const;
